import * as pieces_all from "../assets/";

export const pieces: Record<string, string | null> = {
  Gote_Lance: pieces_all.Gote_Lance,
  Gote_Horse_Knight: pieces_all.Gote_Horse_Knight,
  Gote_Silver: pieces_all.Gote_Silver,
  Gote_Gold: pieces_all.Gote_Gold,
  Gote_King: pieces_all.Gote_King,
  Gote_Rook: pieces_all.Gote_Rook,
  Gote_Bishop: pieces_all.Gote_Bishop,
  Gote_Pawn: pieces_all.Gote_Pawn,
  Gote_Tengu: pieces_all.Gote_Tengu,
  Sente_Lance: pieces_all.Sente_Lance,
  Sente_Horse_Knight: pieces_all.Sente_Horse_Knight,
  Sente_Silver: pieces_all.Sente_Silver,
  Sente_Gold: pieces_all.Sente_Gold,
  Sente_King: pieces_all.Sente_King,
  Sente_Rook: pieces_all.Sente_Rook,
  Sente_Bishop: pieces_all.Sente_Bishop,
  Sente_Pawn: pieces_all.Sente_Pawn,
  Sente_Tengu: pieces_all.Sente_Tengu,

  Gote_Pawn_Reverse: pieces_all.Gote_Pawn_Reverse,
  Gote_Lance_Reverse: pieces_all.Gote_Lance_Reverse,
  Gote_Horse_Knight_Reverse: pieces_all.Gote_Horse_Knight_Reverse,
  Gote_Silver_Reverse: pieces_all.Gote_Silver_Reverse,
  Gote_Rook_Reverse: pieces_all.Gote_Rook_Reverse,
  Gote_Bishop_Reverse: pieces_all.Gote_Bishop_Reverse,
  Gote_Tengu_Reverse: pieces_all.Gote_Tengu_Reverse,

  Sente_Pawn_Reverse: pieces_all.Sente_Pawn_Reverse,
  Sente_Lance_Reverse: pieces_all.Sente_Lance_Reverse,
  Sente_Horse_Knight_Reverse: pieces_all.Sente_Horse_Knight_Reverse,
  Sente_Silver_Reverse: pieces_all.Sente_Silver_Reverse,
  Sente_Rook_Reverse: pieces_all.Sente_Rook_Reverse,
  Sente_Bishop_Reverse: pieces_all.Sente_Bishop_Reverse,
  Sente_Tengu_Reverse: pieces_all.Sente_Tengu_Reverse,

  Empty: null,
}